packages:
  - "artifacts/artifacts/*"
  - "lib/lib/*"
  - "scripts/scripts"

catalog:
  "@replit/vite-plugin-cartographer": "^0.5.5"
  "@replit/vite-plugin-dev-banner": "^0.1.2"
  "@replit/vite-plugin-runtime-error-modal": "^0.0.6"
  "@tailwindcss/vite": "^4.1.6"
  "@tanstack/react-query": "^5.72.3"
  "@types/node": "^22.12.0"
  "@types/react": "^18.3.20"
  "@types/react-dom": "^18.3.5"
  "@vitejs/plugin-react": "^4.3.4"
  "class-variance-authority": "^0.7.1"
  "clsx": "^2.1.1"
  "drizzle-orm": "^0.41.0"
  "framer-motion": "^12.6.0"
  "lucide-react": "^0.475.0"
  "react": "^18.3.1"
  "react-dom": "^18.3.1"
  "tailwind-merge": "^2.6.0"
  "tailwindcss": "^4.1.6"
  "tsx": "^4.19.3"
  "vite": "^6.3.5"
  "zod": "^3.24.1"
